repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
      - id: autopep8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: double-quote-string-fixer
  - repo: local
    hooks:
      - id: isort_ruff
        name: sort_imports
        entry: uv run --frozen ruff --select I001 --fix
        language: system
        types: [python]
      - id: ruff
        name: ruff
        entry: uv run --frozen ruff check
        language: system
        types: [python]
