"""Dash component IDs shared by layout and callbacks."""

TAB_INVESTMENT = 'tab-investment'
TAB_CALCULATION = 'tab-calculation'

STORE_COMPUTE = 'store-compute'
STORE_UPLOAD = 'store-upload'

SELECT_SAVED_VESSEL = 'select-saved-vessel'
SELECT_SAVED_VESSELS_DELETE = 'select-saved-vessels-delete'
BTN_DELETE_SAVED = 'btn-delete-saved'
CONFIRM_DELETE_SAVED = 'confirm-delete-saved'

STORE_ACTIVE_INPUT_SOURCE = 'store-active-input-source'
BTN_INPUT_OPTION_MANUAL = 'btn-input-option-manual'
BTN_INPUT_OPTION_DATABASE = 'btn-input-option-database'
MODAL_UPLOAD = 'modal-upload'
MODAL_DATABASE = 'modal-database'
BTN_MODAL_UPLOAD_CLOSE = 'btn-modal-upload-close'
BTN_MODAL_DATABASE_LOAD = 'btn-modal-database-load'
BTN_MODAL_DATABASE_CLOSE = 'btn-modal-database-close'
BTN_MODAL_DATABASE_CANCEL = 'btn-modal-database-cancel'
INPUT_SOURCE_UPLOAD_WRAP = 'input-source-upload-wrap'
BTN_RESET_BASECASE = 'btn-reset-basecase'

SELECT_COMPARE_A = 'select-compare-a'
SELECT_COMPARE_B = 'select-compare-b'
BTN_COMPARE = 'btn-compare'
CHART_COMPARE = 'chart-compare'
TABLE_COMPARE = 'table-compare'
COMPARE_PLACEHOLDER = 'compare-placeholder'

INPUT_VESSEL_NAME = 'input-vessel-name'
INPUT_PURCHASE_PRICE = 'input-purchase-price'
INPUT_VESSEL_LIFE = 'input-vessel-life'
INPUT_RESIDUAL_VALUE = 'input-residual-value'
INPUT_LW_TONNAGE = 'input-lw-tonnage'
INPUT_REVENUE_PER_DAY = 'input-revenue-per-day'
INPUT_OFFHIRE_RATE = 'input-offhire-rate'
INPUT_OPEX_PER_DAY = 'input-opex-per-day'
INPUT_DRYDOCK_CAPEX = 'input-drydock-capex'
INPUT_DRYDOCK_FREQUENCY = 'input-drydock-frequency'
INPUT_UPGRADES_CAPEX = 'input-upgrades-capex'
INPUT_INFLATION_RATE = 'input-inflation-rate'
INPUT_DISCOUNT_RATE = 'input-discount-rate'
INPUT_DAYS_OF_YEAR = 'input-days-of-year'
INPUT_TEU_SIZE = 'input-teu-size'
INPUT_PURCHASE_DATE = 'input-purchase-date'
INPUT_ENGINE_TYPE = 'input-engine-type'
INPUT_CO2_CARBON_FACTOR = 'input-co2-carbon-factor'

BTN_CALCULATE = 'btn-calculate'
BTN_SAVE_TO_DB = 'btn-save-to-db'
UPLOAD_FILE = 'upload-file'
UPLOAD_SUMMARY_TABLE = 'upload-summary-table'
STORE_UPLOAD_SELECTED_ROW = 'store-upload-selected-row'
UPLOAD_SELECTION_LABEL = 'upload-selection-label'

BANNER_VALIDATION = 'banner-validation'
CARD_NPV = 'card-npv'
CARD_IRR = 'card-irr'
CARD_SIGNAL = 'card-signal'
CARD_BREAKEVEN = 'card-breakeven'
CARD_PAYBACK = 'card-payback'
CHART_SENSITIVITY = 'chart-sensitivity'
INPUT_REV_MIN = 'input-rev-min'
INPUT_REV_MAX = 'input-rev-max'
TABLE_SCENARIOS = 'table-scenarios'

SELECT_SCENARIO = 'select-scenario'
SELECT_CALCULATION_VESSEL = 'select-calculation-vessel'
TABLE_CASHFLOW = 'table-cashflow'
CALCULATION_PLACEHOLDER = 'calculation-placeholder'
