"""Initial schema.

Revision ID: 9f2b93443d45
Revises:
Create Date: 2026-05-31 19:44:36.443108

"""

from collections.abc import Sequence
from datetime import UTC
from datetime import datetime

import sqlalchemy as sa
from alembic import op

_SEED_TS = datetime.now(UTC)


# revision identifiers, used by Alembic.
revision: str = '9f2b93443d45'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'raw_vessel_submissions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('source', sa.String(length=32), nullable=False),
        sa.Column('filename', sa.Text(), nullable=True),
        sa.Column('raw_had_errors', sa.Boolean(), nullable=False),
        sa.Column('raw_payload', sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'vessel_benchmarks',
        sa.Column('teu_bucket', sa.Integer(), nullable=False),
        sa.Column('median_price', sa.Float(), nullable=False),
        sa.Column('vessel_count', sa.Integer(), nullable=False),
        sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('teu_bucket'),
    )
    op.create_table(
        'vessel_inputs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('submission_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('vessel_name', sa.Text(), nullable=False),
        sa.Column('purchase_price', sa.Float(), nullable=False),
        sa.Column('vessel_life', sa.Integer(), nullable=False),
        sa.Column('residual_value', sa.Float(), nullable=False),
        sa.Column('lw_tonnage', sa.Float(), nullable=False),
        sa.Column('revenue_per_day', sa.Float(), nullable=False),
        sa.Column('offhire_rate', sa.Float(), nullable=False),
        sa.Column('opex_per_day', sa.Float(), nullable=False),
        sa.Column('drydock_capex', sa.Float(), nullable=False),
        sa.Column('drydock_frequency', sa.Integer(), nullable=False),
        sa.Column('upgrades_capex', sa.Float(), nullable=False),
        sa.Column('inflation_rate', sa.Float(), nullable=False),
        sa.Column('discount_rate', sa.Float(), nullable=False),
        sa.Column('days_of_year', sa.Integer(), nullable=False),
        sa.Column('teu_size', sa.Integer(), nullable=False),
        sa.Column('purchase_date', sa.Date(), nullable=False),
        sa.Column('engine_type', sa.Text(), nullable=True),
        sa.Column('co2_carbon_factor', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ['submission_id'],
            ['raw_vessel_submissions.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'vessel_valuations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('vessel_input_id', sa.Integer(), nullable=False),
        sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('npv', sa.Float(), nullable=False),
        sa.Column('irr', sa.Float(), nullable=True),
        sa.Column('payback_year', sa.Integer(), nullable=True),
        sa.Column('investment_signal', sa.String(length=32), nullable=False),
        sa.Column('breakeven_rate', sa.Float(), nullable=True),
        sa.Column('sensitivity', sa.JSON(), nullable=True),
        sa.Column('scenarios', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ['vessel_input_id'],
            ['vessel_inputs.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'vessel_cashflow_years',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('valuation_id', sa.Integer(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('period_end', sa.Date(), nullable=False),
        sa.Column('revenue', sa.Float(), nullable=False),
        sa.Column('opex', sa.Float(), nullable=False),
        sa.Column('drydock_capex', sa.Float(), nullable=False),
        sa.Column('upgrades_capex', sa.Float(), nullable=False),
        sa.Column('free_cashflow', sa.Float(), nullable=False),
        sa.Column('net_cashflow', sa.Float(), nullable=False),
        sa.Column('discounted_cashflow', sa.Float(), nullable=False),
        sa.Column('cumulative_cashflow', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ['valuation_id'],
            ['vessel_valuations.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('valuation_id', 'year', name='uq_valuation_year'),
    )
    benchmark_table = sa.table(
        'vessel_benchmarks',
        sa.column('teu_bucket', sa.Integer()),
        sa.column('median_price', sa.Float()),
        sa.column('vessel_count', sa.Integer()),
        sa.column('last_updated', sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        benchmark_table,
        [
            {
                'teu_bucket': 7000,
                'median_price': 80_000_000.0,
                'vessel_count': 0,
                'last_updated': _SEED_TS,
            },
            {
                'teu_bucket': 8000,
                'median_price': 90_000_000.0,
                'vessel_count': 0,
                'last_updated': _SEED_TS,
            },
            {
                'teu_bucket': 10000,
                'median_price': 100_000_000.0,
                'vessel_count': 0,
                'last_updated': _SEED_TS,
            },
            {
                'teu_bucket': 12000,
                'median_price': 115_000_000.0,
                'vessel_count': 0,
                'last_updated': _SEED_TS,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vessel_cashflow_years')
    op.drop_table('vessel_valuations')
    op.drop_table('vessel_inputs')
    op.drop_table('vessel_benchmarks')
    op.drop_table('raw_vessel_submissions')
    # ### end Alembic commands ###
